[path]
source = "D:\\structFolder"
target = "D:\\structTest"

[picture]
logo = "C:\\Users\\Tom\\Desktop\\d74c9f7080b4d39e27371fbd4e6d9e6e.jpg"
logos = "C:\\Users\\Tom\\Desktop\\d74c9f7080b4d39e27371fbd4e6d9e6e.jpg"
background = "C:/Users/Tom/Desktop/d74c9f7080b4d39e27371fbd4e6d9e6e.jpg"